---
- hosts: all
  become: yes
  tasks:
  - name: Install apache server
    yum:
      name: httpd
      state: present
  - name: Ensure apache service is runnning
    service:
       name: httpd
       state: started
       enabled: yes
