---
- hosts: webserver
  become: yes
  tasks:
  - name: update packages for Debian
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: install apache for Debain
    apt:
      name: "{{ pack_name }}"
      state: present
    notify:
    - Restart Apache
    when: ansible_os_family =="Debian"
  - name: install apache for RedHat
    yum:
      name: "{{ pack_name }}"
      state: present
    notify:
    - Restart Apache
    when: ansible_os_family == "RedHat"
  - name: Backup of Home page
    command: cp -n {{ homepage }} {{ backuppath }}
  - name: Create the home page
    copy:
      dest: "{{ homepage }}"
      content: "<h1> Welcome To Apache (Controlled By Ansible) </h1>"
    notify:
    - Restart Apache
  handlers:
  - name: Restart Apache
    service:
      name: "{{ pack_name }}"
      state: restarted


