---
- hosts: all
  become: yes
  vars:
  - pack_name: apache2
  - php_packages:
    - php 
    - php-mysql
  tasks:
  - name: install apache server
    package:
      name: "{{ pack_name }}"
      state: present
    notify:
    - restart apache 
  - name: install php packages
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ php_packages }}"
    notify:
    - restart apache
  - name: download web page
    get_url:
      url: https://raw.githubusercontent.com/asquarezone/AnsibleZone/master/ClassRoomExamples/July2018/basics/info.php
      dest: /var/www/html/info.php
    notify:
    - restart apache 
    - restart httpd    
  handlers:
  - name: restart apache
    service:
      name: "{{ pack_name }}"
      state: restarted     