# ansible -m ping all
#play
---
- hosts: all
  become: yes
  tasks:
  - name: Execute ansible ping on hosts
    ping: 
  - name: Update packages on ubuntu
    apt:
      name: git
      update_cache: yes
      state: present
  - name: install tree
    apt:
      name: tree
      state: present    

