---
- hosts: all
  become: yes
  tasks:
  - name: install webserver
    package:
      name: "{{ package_name }}"
      state: present
  - name:  update package
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: "testtask for {{ansible_os_family}}"
    when: ansible_os_family == "RedHat"

  - name: "install utilities"
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    - tree
    - nano
    

# ansible-playbook -i "inventory/hosts" webserver.yaml